### ISSUE TITLE
Zaimplementować Selekcję

### ISSUE THREAD

**Issue by KostkaBrukowa** [KostkaBrukowa/dorothea_classifier#4]
Twoim zadaniem będzie zaimplementować trzy algorytmy selekcji podane w dokumentacji.
Iterface tych algorytmów powinien wygladać tak (to moga być funkcje albo klasy mi to rybka): 
- na wejście dostanie typ `PopulationWithFitness = List[Tuple[float, np.ndarray]]` czyli lista osobników z fitnessem (wartościa funkji celu) gdzie `float` to wartość a `np.ndarray` to osobnik. 
- na wyściu chcę otrzymać `List[Tuple[int, int]]` gdzie jest to lista o rozmiarze `2 * len(populacja_podana_w_argumencie)` a elementami sa wybrane pary (indeksy tych osobników) przez selekcję. 
- przykładowa definicja funkcji 
```python
def dupa(population_with_fitness: PopulationWithFitness) -> List[Tuple[int, int]]:
    ...
```
- możesz także uzupełnić ENUM w pliku algorithm.py o twoje algorytmy

**Comment by kejbi** [comment]
> na wyściu chcę otrzymać List[Tuple[int, int]] gdzie jest to lista o rozmiarze 2 * len(populacja_podana_w_argumencie) a elementami sa wybrane pary (indeksy tych osobników) przez selekcję.

serio aż 2 razy większą? czyli osobniki mogą się rozmnażać kilka razy?
